name: pspdfkit_example
description: Demonstrates how to use the pspdfkit plugin.
version: 3.6.0

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=3.7.5'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  http: ^0.13.5
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

  pspdfkit_flutter:
    path: ../

flutter:

  uses-material-design: true

  assets:
    - PDFs/
    - PDFs/Instant/
